/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class BOOK extends javax.swing.JFrame {

    /** Creates new form BOOK */
    public BOOK() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        TP = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        C = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        UN = new javax.swing.JTextField();
        D = new javax.swing.JComboBox<>();
        S = new javax.swing.JComboBox<>();
        jDateChooser2 = new datechooser.beans.DateChooserCombo();
        jDateChooser1 = new datechooser.beans.DateChooserCombo();
        CC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        B = new javax.swing.JRadioButton();
        A = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book");
        setBackground(new java.awt.Color(165, 55, 253));
        setMaximumSize(new java.awt.Dimension(1049, 563));
        setMinimumSize(new java.awt.Dimension(1049, 563));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(219, 10, 91));
        jLabel3.setText("Source ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 158, 100, 43));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(219, 10, 91));
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 161, 156, 39));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(219, 10, 91));
        jLabel5.setText("Date of Departure");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(219, 10, 91));
        jLabel6.setText("Date of Arrival");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 241, -1, 34));

        jButton1.setBackground(new java.awt.Color(240, 52, 52));
        jButton1.setFont(new java.awt.Font("Candara", 1, 23)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book Flight");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 200, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(219, 10, 91));
        jLabel2.setText("TICKET PRICE(IN SR)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 374, 300, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(219, 10, 91));
        jLabel7.setText("TOTAL PRICE ( IN RS )");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 375, -1, -1));

        P.setBackground(new java.awt.Color(108, 122, 137));
        P.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        P.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 378, 176, 26));

        TP.setBackground(new java.awt.Color(108, 122, 137));
        TP.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        getContentPane().add(TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 374, 176, 26));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(219, 10, 91));
        jLabel10.setText("CLASS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, -1));

        C.setBackground(new java.awt.Color(189, 195, 199));
        C.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        C.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First", "Buisness Class B1", "Buisness Class B2", "Premium Economy Class", "Economy Class" }));
        C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 310, 176, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(219, 10, 91));
        jLabel11.setText("No. Of Tickets");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 310, 190, 26));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 310, 176, -1));

        jLabel14.setBackground(new java.awt.Color(102, 255, 204));
        jLabel14.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("User Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 95, 160, -1));

        UN.setBackground(new java.awt.Color(108, 122, 137));
        UN.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        UN.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 90, 260, -1));

        D.setBackground(new java.awt.Color(189, 195, 199));
        D.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        D.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Australia", "Austria", "Belgium", "Brazil", "Canada", "China", "Colombia", "Croatia", "Egypt", "France", "Germany", "Holland", "India", "Ireland", "Italy", "Japan", "Malalysia", "Mexico", "Morocco", "Nepal", "New Zealand", "Norway", "Portugal", "Russia", "Singapore", "Spain", "Switzerland", "United Arab Emirates", "United Kingdom", "United States of America" }));
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 170, 176, 26));

        S.setBackground(new java.awt.Color(189, 195, 199));
        S.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        S.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Australia", "Austria", "Belgium", "Brazil", "Canada", "China", "Colombia", "Croatia", "Egypt", "France", "Germany", "Holland", "India", "Ireland", "Italy", "Japan", "Malalysia", "Mexico", "Morocco", "Nepal", "New Zealand", "Norway", "Portugal", "Russia", "Singapore", "Spain", "Switzerland", "United Arab Emirates", "United Kingdom", "United States of America" }));
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 168, 176, -1));

        jDateChooser2.setCalendarBackground(new java.awt.Color(108, 122, 137));
        jDateChooser2.setNothingAllowed(false);
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 241, 176, -1));

        jDateChooser1.setCalendarBackground(new java.awt.Color(108, 122, 137));
        jDateChooser1.setNothingAllowed(false);
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 241, 176, -1));

        CC.setBackground(new java.awt.Color(108, 122, 137));
        CC.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        CC.setForeground(new java.awt.Color(255, 255, 255));
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });
        getContentPane().add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 442, 176, 30));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(219, 10, 91));
        jLabel13.setText("CARD NUMBER ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 442, -1, 26));

        B.setBackground(new java.awt.Color(46, 49, 49));
        B.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        B.setForeground(new java.awt.Color(255, 255, 255));
        B.setText("DEBIT CARD");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        A.setBackground(new java.awt.Color(46, 49, 49));
        A.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("CREDIT CARD");
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 439, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 23)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(219, 10, 91));
        jLabel12.setText("Payment Method");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 441, -1, -1));

        jButton2.setBackground(new java.awt.Color(31, 58, 147));
        jButton2.setFont(new java.awt.Font("Candara", 1, 23)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 190, -1));

        jButton3.setBackground(new java.awt.Color(31, 58, 147));
        jButton3.setFont(new java.awt.Font("Candara", 1, 23)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Go Back ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 190, -1));

        jButton4.setBackground(new java.awt.Color(240, 52, 52));
        jButton4.setFont(new java.awt.Font("Candara", 1, 23)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Show Amount");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 200, -1));

        jPanel2.setBackground(new java.awt.Color(140, 20, 252));

        jLabel1.setBackground(new java.awt.Color(165, 55, 253));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("      Booking");

        jLabelMin.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(501, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabelClose)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1182, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\amima\\Desktop\\Fly-Airlines-PPT-Backgrounds.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String UserName , CardNo;
        CardNo=CC.getText();
        UserName = UN.getText();
         if (UserName.isEmpty()==true || (A.isSelected()==false && B.isSelected()==false)|| CardNo.isEmpty()==true)
         { JOptionPane.showMessageDialog(this, "User Name or Card No. not entered or Payment Method not selected !");}
          else   
                 
             {
                 String Source = S.getSelectedItem().toString();
                 String Destination = D.getSelectedItem().toString();
                 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                 String dod = sdf.format(jDateChooser1.getSelectedDate().getTime());
                 SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                 String doa = df.format(jDateChooser2.getSelectedDate().getTime());
                 double  price= 0;
                 switch (C.getSelectedIndex()) {
                     case 0:
                         price=10000 ;
                         break;
                     case 1:
                         price=7500;
                         break;
                     case 2:
                         price=6500;
                         break;
                     case 3:
                         price=4500;
                         break;
                     case 4:
                         price=3500;
                         break;
                     default:
                         break;
                 }
                 
                 P.setText(Double.toString(price));
                 
                 Object n=jSpinner1.getValue();
                 int t =Integer.parseInt(n.toString());
                 
                 Double tp= t*price;
                 TP.setText(Double.toString(tp));
                 
                 {
                     try{
                         Class.forName("java.sql.DriverManager");
                         Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Air", "root", "12345");
                         Statement stmt = (Statement)con.createStatement();
                         String query = "Insert into Cust_Info Values( '"+UserName+"','"+Source+"', '"+dod+"', '"+Destination+"','"+doa+"') ;";
                        int x =stmt.executeUpdate(query);
                         if (x!=0)
                        
                         {JOptionPane.showMessageDialog(this,  "Booking Successful ! Have a Safe and Happy Journey !");
                        
                        MainPage lgf= new MainPage();
                        lgf.setVisible(true);
                        lgf.pack();
                        lgf.setLocationRelativeTo(null);
                        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                        } 
                         
                         else                    
                         {
                             JOptionPane.showMessageDialog(this, "User Name does not exist!");
                             
                         } 
                         
                         }
                     
                     catch(HeadlessException | ClassNotFoundException | SQLException e)
                     {
                         JOptionPane.showMessageDialog(this,"Please Register in order to book ");
                     }
                     
                     
                     
                 }
                 
             }
         
        
    }//GEN-LAST:event_jButton1ActionPerformed
         
    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        



    // TODO add your handling code here:
    }//GEN-LAST:event_CCActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  CC.setText("");
    UN.setText("");  
    P.setText("");
    TP.setText("");
    C.setSelectedIndex(0);
    S.setSelectedIndex(0);
    D.setSelectedIndex(0);
    A.setSelected(false);
    B.setSelected(false);




// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
MainPage lgf= new MainPage();
  lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

// TODO add your handling code here:
  
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  
 double  price= 0;
                 switch (C.getSelectedIndex()) {
                     case 0:
                         price=10000 ;
                         break;
                     case 1:
                         price=7500;
                         break;
                     case 2:
                         price=6500;
                         break;
                     case 3:
                         price=4500;
                         break;
                     case 4:
                         price=3500;
                         break;
                     default:
                         break;
                 }
                 
                 P.setText(Double.toString(price));
                 
                 Object n=jSpinner1.getValue();
                 int t =Integer.parseInt(n.toString());
                 
                 Double tp= t*price;
                 TP.setText(Double.toString(tp));



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOOK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JComboBox C;
    private javax.swing.JTextField CC;
    private javax.swing.JComboBox<String> D;
    private javax.swing.JLabel P;
    private javax.swing.JComboBox<String> S;
    private javax.swing.JLabel TP;
    private javax.swing.JTextField UN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private datechooser.beans.DateChooserCombo jDateChooser1;
    private datechooser.beans.DateChooserCombo jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

}
