
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * manage.java
 *
 * Created on Oct 10, 2018, 1:45:13 PM
 */

/**
 *
 * @author ayasr
 */
public class manage extends javax.swing.JFrame {

    private Statement stmt;

    /** Creates new form manage */
    public manage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        UN = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage an existing Booking");
        setMaximumSize(new java.awt.Dimension(679, 580));
        setMinimumSize(new java.awt.Dimension(679, 580));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton3.setBackground(new java.awt.Color(31, 58, 147));
        jButton3.setFont(new java.awt.Font("Candara", 1, 23)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Go Back ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 490, 180, 37);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("          \n          To access an existing booking, please enter your name below.\n                      You can review or change your flight details.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 110, 495, 77);

        jButton1.setBackground(new java.awt.Color(153, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Retrieve Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 490, 190, 40);

        UN.setBackground(new java.awt.Color(189, 195, 199));
        UN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNActionPerformed(evt);
            }
        });
        getContentPane().add(UN);
        UN.setBounds(280, 220, 210, 40);

        jScrollPane2.setBackground(new java.awt.Color(51, 0, 204));

        Table1.setBackground(new java.awt.Color(52, 73, 94));
        Table1.setForeground(new java.awt.Color(255, 255, 255));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Source", "DepartureDate", "Destination", "ArrivalDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 300, 590, 130);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Manage An Existing Booking");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 530, 42);

        jLabelMin.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(153, 0, 153));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelMin);
        jLabelMin.setBounds(590, 10, 20, 30);

        jLabelClose.setBackground(new java.awt.Color(51, 153, 255));
        jLabelClose.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(153, 0, 153));
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelClose);
        jLabelClose.setBounds(630, 10, 20, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 680, 70);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("User Name ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 230, 130, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\amima\\Desktop\\jhd.JPG")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 50, 690, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String u= UN.getText();
        DefaultTableModel model=(DefaultTableModel)Table1.getModel();

    try 
    {
    Class.forName("java.sql.DriverManager");
    Connection con=(Connection)
             DriverManager.getConnection("jdbc:mysql://localhost:3306/air","root","12345");
    Statement stmt=(Statement)con.createStatement();
    String query="Select*from Cust_Info where UserName='"+u+"';";
        ResultSet rs=stmt.executeQuery(query);
        if(rs.next())
        {
            String UserName=rs.getString("UserName");
            String Source=rs.getString("Source");
            String DepartureDate=rs.getString("DepartureDate");
            String Destination=rs.getString("Destination");
            String ArrivalDate=rs.getString("ArrivalDate");
            model.addRow(new Object[]{UserName,Source,DepartureDate,Destination,ArrivalDate});
        }
        else
        { JOptionPane.showMessageDialog(this, "No booking found !");}
    }
    catch(ClassNotFoundException | SQLException e)
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
            
        }
    


    }//GEN-LAST:event_jButton1ActionPerformed

private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
    this.setState(JFrame.ICONIFIED);
    // TODO add your handling code here:
}//GEN-LAST:event_jLabelMinMouseClicked

private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
    System.exit(0);

    // TODO add your handling code here:
}//GEN-LAST:event_jLabelCloseMouseClicked

    private void UNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainPage lgf= new MainPage();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JTextField UN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
